### ISSUE TITLE
Youtube 기존 주소를 .mp4 주소로 변환

### ISSUE THREAD

**Issue by hyewon000** [jehyeon/KidsBi#2]
https://medium.com/@svdoever/convert-youtube-url-to-mp4-url-f371d9574b7

참고용 사이트

현재 인빅스비로 영상을 재생할 때 .mp4 주소가 필요하기 때문에
해당 주소 변환 방법 찾아봐야 함

**Comment by jehyeon** [comment]
https://r5---sn-n3cgv5qc5oq-bh2sd.googlevideo.com/videoplayback?expire=1572193273&ei=mW-1XYq0MpDrgAOR1JEY&ip=58.233.83.92&id=o-AA1A51iJVnPM_oW9x18EPo_ci1MhwjrGV25VJHsXMB2N&itag=22&source=youtube&requiressl=yes&mm=31%2C26&mn=sn-n3cgv5qc5oq-bh2sd%2Csn-i3b7knsl&ms=au%2Conr&mv=m&mvi=4&pl=19&initcwndbps=1430000&mime=video%2Fmp4&ratebypass=yes&dur=217.501&lmt=1540895345078437&mt=1572171551&fvip=5&fexp=23842630&c=WEB&txp=5431432&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cmime%2Cratebypass%2Cdur%2Clmt&sig=ALgxI2wwRAIgXXoJw8j4fbO-f-xma1zGRnXTDXgFusNuzOfw-S5St5kCIAZYoG1mFXiMpy7zFKtds69X3ahaKOOTVG4g7jWs86k4&lsparams=mm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AHylml4wRQIgUceu8AH2uFS7ebxhMrVhkg_W1CGvlTB2UWt4EixjIYECIQDgYPLXW98JKOsnEizHtD-wTFhJ95-KWdFJYlPqHEhi-g%3D%3D

https://r5---sn-n3cgv5qc5oq-bh2sd.googlevideo.com/videoplayback?expire=1572193273&ei=mW-1XYq0MpDrgAOR1JEY&ip=58.233.83.92&id=o-AA1A51iJVnPM_oW9x18EPo_ci1MhwjrGV25VJHsXMB2N&itag=22&source=youtube&requiressl=yes&mm=31%2C26&mn=sn-n3cgv5qc5oq-bh2sd%2Csn-i3b7knsl&ms=au%2Conr&mv=m&mvi=4&pl=19&initcwndbps=1430000&mime=video%2Fmp4&ratebypass=yes&dur=217.501&lmt=1540895345078437&mt=1572171551&fvip=5&fexp=23842630&c=WEB&txp=5431432&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cmime%2Cratebypass%2Cdur%2Clmt&sig=ALgxI2wwRAIgXXoJw8j4fbO-f-xma1zGRnXTDXgFusNuzOfw-S5St5kCIAZYoG1mFXiMpy7zFKtds69X3ahaKOOTVG4g7jWs86k4&lsparams=mm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AHylml4wRQIgUceu8AH2uFS7ebxhMrVhkg_W1CGvlTB2UWt4EixjIYECIQDgYPLXW98JKOsnEizHtD-wTFhJ95-KWdFJYlPqHEhi-g%3D%3D

**Comment by jehyeon** [comment]
https://github.com/jehyeon/KidsBi/commit/7ca6f3b98fc6b7a65c47419691838b71ccf9b886  https://github.com/jehyeon/KidsBi/commit/b0a5593f0e6f2b6bb76e8131b40457eb1907ddc2

**Comment by jehyeon** [comment]
https://github.com/jehyeon/KidsBi/commit/7ca6f3b98fc6b7a65c47419691838b71ccf9b886   

https://github.com/jehyeon/KidsBi/commit/b0a5593f0e6f2b6bb76e8131b40457eb1907ddc2

**Comment by jehyeon** [comment]
https://github.com/jehyeon/KidsBi/commit/7ca6f3b98fc6b7a65c47419691838b71ccf9b886
